# Generated by Django 5.0.6 on 2024-07-09 12:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_extension', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='photo',
        ),
    ]
