# Generated by Django 5.0.6 on 2024-07-09 15:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_extension', '0003_employee_photo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Extenson',
        ),
    ]
