# Generated by Django 5.0.6 on 2024-07-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id_creator',
            field=models.TextField(null=True),
        ),
    ]
