# Generated by Django 5.0.6 on 2024-07-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_id_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='photo_creator',
            field=models.TextField(null=True),
        ),
    ]
