# Generated by Django 5.0.6 on 2024-07-12 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='id_creator',
            field=models.TextField(null=True),
        ),
    ]
